services:
  db:
    image: mysql:8
    container_name: db_container
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_password
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_user_pass
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    expose:
      - "5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my_secret_password
      - DB_NAME=app_db
    volumes:
      - ./app_logs:/app/logs
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  db_data:
